version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - curl -fsSLO "https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip"
      - unzip terraform_0.15.3_linux_amd64.zip -d /usr/local/bin
      - npm install -g npm
  pre_build:
    commands:
      - touch .npmrc
      - echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
      - echo "//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" >> .npmrc
      - npm i
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - terraform init -backend-config="token=$TF_CLOUD_TOKEN"
      - terraform apply -auto-approve -input=false
      - aws s3 sync ./web/build s3://crowdq.fm
      - aws s3 sync ./server/dist s3://crowdq-fm-server-dist
